[package]
name = "questionly0/topbarplus"
description = "Forked from Emotes-CO/TopbarPlus, removed Gamepad.lua."
license = "MPL2"
version = "3.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
    "default.project.json",
    "src",
    "src/**",
    "LICENSE",
    "wally.toml",
]

[dependencies]